### ISSUE TITLE
Synchronization: P-SUD => local infrastructure

### ISSUE THREAD

**Issue by samuelvonstachelski** [i4Ds/FLARECAST#12]
Add sync-mechanism to hmi- and property service. The synchronisation should be triggered in the management console.

**Comment by samuelvonstachelski** [comment]
Right now people can download files from P-SUD via SSH connection and browser

**Comment by marcosoldati** [comment]
Moved to Jira
https://dev.flarecast.eu/jira/projects/INFRA/issues/INFRA-27
